/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/audit/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export audit logs as CSV or JSON. */
    get: operations["get_export_audit_logs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get audit logs with filtering and pagination. */
    get: operations["get_get_audit_logs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/confirm-email/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm a user's email address with a confirmation token.
     * @description Both helpers are async coroutines; awaiting them directly (rather than
     *     scheduling them on an executor, which would just hand back an
     *     un-awaited coroutine object) is what actually runs the DB work.
     */
    post: operations["post_confirm_email_endpoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password reset link.
     * @description Unauthenticated. Always answers with :data:`PASSWORD_RESET_ACK` and 200,
     *     whether or not the address is registered, and never returns the reset
     *     token itself.
     *
     *     Both properties are load-bearing security controls, not cosmetics:
     *     returning the token handed any anonymous caller a full account takeover
     *     for any address they could name, and returning a distinct message for
     *     the not-found case made the endpoint a user-enumeration oracle. Any
     *     change here that reintroduces a branch-dependent body reintroduces one
     *     of those two bugs.
     */
    post: operations["post_forgot_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login endpoint - returns access and refresh tokens. */
    post: operations["post_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout endpoint - revokes all refresh tokens for user. */
    post: operations["post_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user profile. */
    get: operations["get_get_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/oauth/connections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get OAuth connections for current user. */
    get: operations["get_get_oauth_connections"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Redirect to OAuth provider for authorization. */
    get: operations["get_oauth_redirect"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/oauth/{provider}/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Handle OAuth2 callback and create/link user account. */
    get: operations["get_oauth_callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/oauth/{provider}/disconnect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disconnect OAuth connection for current user. */
    post: operations["post_disconnect_oauth"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchange a refresh token for a new token pair, rotating the old one.
     * @description Rotation is one-use: the presented token is revoked before its
     *     replacement is issued, so replaying it afterwards fails even if
     *     issuance errors partway through.
     */
    post: operations["post_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register new user (creates viewer role by default + personal team). */
    post: operations["post_register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset password with token. */
    post: operations["post_reset_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List active sessions for the authenticated user. */
    get: operations["get_list_sessions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke one of the authenticated user's sessions. */
    delete: operations["delete_revoke_session_endpoint"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dashboard/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Recent audit events for the tenant. */
    get: operations["get_dashboard_activity"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dashboard/alerts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Aggregated alerts — products with non-healthy status. */
    get: operations["get_dashboard_alerts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dashboard/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health matrix for all products. */
    get: operations["get_dashboard_health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dashboard/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Aggregated stats for all products in the current tenant. */
    get: operations["get_dashboard_overview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/discovery/accept/{discovery_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept a discovered product and create a connection. */
    post: operations["post_accept_discovered_product"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/discovery/results": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get latest scan results. */
    get: operations["get_get_scan_results"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/discovery/scan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger a network scan for PenguinTech products.
     * @description Requires owner/admin authority on the tenant, and scans only addresses
     *     inside the operator's DISCOVERY_RANGES allowlist. Caller-supplied
     *     ``ranges`` narrow that allowlist; they can never widen it.
     */
    post: operations["post_trigger_scan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hello": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Hello world endpoint - requires authentication. */
    get: operations["get_hello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hello/protected": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Protected hello - requires maintainer or admin role. */
    get: operations["get_hello_protected"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/license/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get license status.
     * @description Returns:
     *         JSON response with license details (admin only).
     */
    get: operations["get_get_license_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mfa/backup-codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** View backup codes. */
    get: operations["get_get_backup_codes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mfa/backup-codes/regenerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Regenerate backup codes. */
    post: operations["post_regenerate_backup_codes"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mfa/disable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disable MFA (requires password and TOTP verification). */
    post: operations["post_disable_mfa_endpoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mfa/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate TOTP secret and QR code for 2FA setup. */
    post: operations["post_setup_mfa"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mfa/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify TOTP code and enable MFA. */
    post: operations["post_verify_mfa"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List connected products for current tenant. */
    get: operations["get_list_products"];
    put?: never;
    /** Register a new product connection (manual). */
    post: operations["post_register_product"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all available product types with metadata. */
    get: operations["get_list_product_types"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{connection_id}/proxy/{proxy_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Forward request to a connected product's API.
     * @description Deny-by-default: request must match adapter's route_allowlist.
     */
    get: operations["get_proxy_request"];
    /**
     * Forward request to a connected product's API.
     * @description Deny-by-default: request must match adapter's route_allowlist.
     */
    put: operations["put_proxy_request"];
    /**
     * Forward request to a connected product's API.
     * @description Deny-by-default: request must match adapter's route_allowlist.
     */
    post: operations["post_proxy_request"];
    /**
     * Forward request to a connected product's API.
     * @description Deny-by-default: request must match adapter's route_allowlist.
     */
    delete: operations["delete_proxy_request"];
    /**
     * Forward request to a connected product's API.
     * @description Deny-by-default: request must match adapter's route_allowlist.
     */
    options: operations["options_proxy_request"];
    head?: never;
    /**
     * Forward request to a connected product's API.
     * @description Deny-by-default: request must match adapter's route_allowlist.
     */
    patch: operations["patch_proxy_request"];
    trace?: never;
  };
  "/api/v1/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get product connection details. */
    get: operations["get_get_product"];
    /** Update product connection config. */
    put: operations["put_update_product"];
    post?: never;
    /** Remove product connection. */
    delete: operations["delete_delete_product"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get latest health status for a product. */
    get: operations["get_get_product_health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}/schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get management schema (available actions) for a product. */
    get: operations["get_get_product_schema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}/tenants/{tenant_id}/map": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get product tenant external mapping. */
    get: operations["get_get_product_tenant_mapping"];
    /** Update product tenant external mapping. */
    put: operations["put_update_product_tenant_mapping"];
    /** Set product tenant external mapping. */
    post: operations["post_set_product_tenant_mapping"];
    /** Delete product tenant external mapping. */
    delete: operations["delete_delete_product_tenant_mapping"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test a product connection. */
    post: operations["post_test_product_connection"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public status endpoint - no authentication required. */
    get: operations["get_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/teams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List user's teams. */
    get: operations["get_list_user_teams"];
    put?: never;
    /** Create new team (authenticated users). */
    post: operations["post_create_team_endpoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/teams/invitations/{token}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept team invitation. */
    post: operations["post_accept_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/teams/{team_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get team details (team members only). */
    get: operations["get_get_team_endpoint"];
    /** Update team (team admin only). */
    put: operations["put_update_team_endpoint"];
    post?: never;
    /** Delete team (owner only). */
    delete: operations["delete_delete_team_endpoint"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/teams/{team_id}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send team invitation via email. */
    post: operations["post_send_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/teams/{team_id}/invitations/{invite_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Cancel team invitation (team admin only). */
    delete: operations["delete_cancel_invitation"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/teams/{team_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List team members. */
    get: operations["get_list_team_members"];
    put?: never;
    /** Add member to team (team admin only). */
    post: operations["post_add_team_member_endpoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/teams/{team_id}/members/{member_user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update member role (team admin only). */
    put: operations["put_update_member_role"];
    post?: never;
    /** Remove member from team (team admin only). */
    delete: operations["delete_remove_team_member"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List user's tenants (with optional subtree expansion).
     * @description Query params:
     *       - include_children=true: also list tenants in subtrees the caller
     *         administers. Those rows come back as TenantSummary, not
     *         TenantDetail: holding admin over an ancestor grants the right to
     *         know a descendant exists, not to read its plan, quotas or owner
     *         without switching into it.
     */
    get: operations["get_list_user_tenants"];
    put?: never;
    /**
     * Create new tenant, optionally beneath an existing parent tenant.
     * @description ``parent_tenant_id`` is what makes a hierarchy constructible at all: with
     *     no way to set it at creation, every tenant is a root and the delegated
     *     admin model has nothing to delegate over. The parent is validated for
     *     existence, caller authority, and depth before any row is written.
     */
    post: operations["post_create_tenant_endpoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants/{tenant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tenant details (members and delegated admins only). */
    get: operations["get_get_tenant_endpoint"];
    /** Update tenant (holders of tenants:manage, incl. delegated admins). */
    put: operations["put_update_tenant_endpoint"];
    post?: never;
    /**
     * Delete tenant (owner only).
     * @description Stays strictly owner-gated at both layers. ``tenants:delete`` appears in
     *     the owner bundle alone — notably NOT in the delegated-admin bundle,
     *     which is what keeps delegation conferring management rather than
     *     destruction of a tenant somebody else owns. The ownership check below
     *     is retained on top: the scope answers "an owner of this tenant", the
     *     row check answers "*the* owner", and only the second is authoritative
     *     for an irreversible delete.
     */
    delete: operations["delete_delete_tenant_endpoint"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants/{tenant_id}/dashboard/rollup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get per-child-tenant × per-product rollup for provider dashboard.
     * @description Available to holders of ``tenants:manage`` here, which includes admins
     *     acting by delegation from an ancestor. Product health is stubbed until
     *     the Phase 4 adapters land; the product identity is not — it comes from
     *     ``product_type``.
     */
    get: operations["get_get_dashboard_rollup"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants/{tenant_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List tenant members.
     * @description Now reachable by delegated admins as well as direct members, which is
     *     precisely why the rows go through TenantMemberResponse: get_tenant_members
     *     returns raw joined rows, so a wider audience on the endpoint would have
     *     meant a wider audience for every column that join happens to carry.
     */
    get: operations["get_list_tenant_members"];
    put?: never;
    /** Add member to tenant (holders of members:manage, incl. delegated). */
    post: operations["post_add_tenant_member_endpoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants/{tenant_id}/members/{member_user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update member role (holders of members:manage, incl. delegated). */
    put: operations["put_update_tenant_member_role"];
    post?: never;
    /** Remove member from tenant (holders of members:manage, incl. delegated). */
    delete: operations["delete_remove_tenant_member"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants/{tenant_id}/parent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Move a tenant (and its subtree) under a new parent, or to a root.
     * @description Requires admin authority in BOTH the tenant being moved and the
     *     destination parent — moving a subtree under a parent you administer is
     *     a grant of authority over that subtree, so authority over only one side
     *     is not enough. Rejects cycles, maintains ``depth`` for the whole moved
     *     subtree, and invalidates caches on both the old and new ancestor chains.
     */
    put: operations["put_reparent_tenant_endpoint"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants/{tenant_id}/switch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Switch active tenant — returns a new JWT scoped to it.
     * @description Allowed if the caller is a direct member of the tenant, or holds
     *     admin/owner in one of its ancestors (delegated MSP admin).
     *
     *     Authorization runs BEFORE the existence/active check on purpose. The
     *     other order answers "does tenant 4127 exist?" for any authenticated
     *     user, because a non-existent tenant 404s while a real one they cannot
     *     reach 403s. Now every unauthorized caller sees the same 403 regardless.
     */
    post: operations["post_switch_tenant"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tenants/{tenant_id}/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tenant resource usage and quotas. */
    get: operations["get_get_tenant_usage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all users with pagination (Admin only). */
    get: operations["get_get_users"];
    put?: never;
    /** Create new user (Admin only). */
    post: operations["post_create_new_user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/api-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List user's API keys. */
    get: operations["get_list_api_keys"];
    put?: never;
    /** Create new API key. */
    post: operations["post_create_api_key_endpoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/api-keys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke an API key. */
    delete: operations["delete_delete_api_key"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/audit-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get audit logs (Admin only). */
    get: operations["get_get_audit_logs_endpoint"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get own profile. */
    get: operations["get_get_profile"];
    /** Update own profile. */
    put: operations["put_update_profile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Change own password. */
    put: operations["put_change_password"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get list of valid roles (Admin only). */
    get: operations["get_get_roles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get single user by ID (Admin only). */
    get: operations["get_get_user"];
    /** Update user by ID (Admin only). */
    put: operations["put_update_existing_user"];
    post?: never;
    /** Delete user by ID (Admin only). */
    delete: operations["delete_delete_existing_user"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check endpoint.
     * @description Tests database connectivity by attempting a simple query.
     */
    get: operations["get_health_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness check endpoint. */
    get: operations["get_readiness_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * RollupEntry
     * @description Per-tenant rollup row.
     */
    RollupEntry: {
      /** Products */
      products: components["schemas"]["RollupProduct"][];
      /** Tenant Id */
      tenant_id: number;
      /** Tenant Name */
      tenant_name: string;
    };
    /**
     * RollupProduct
     * @description One product connection's status inside a rollup row.
     */
    RollupProduct: {
      /** Connection Id */
      connection_id: number;
      /** Product */
      product: string;
      /** Status */
      status: string;
    };
    /**
     * TenantDetail
     * @description The projection a member (or delegated admin) may see.
     */
    TenantDetail: {
      /** Depth */
      depth: number;
      /** Display Name */
      display_name: string;
      /** Id */
      id: number;
      /** Kind */
      kind: string;
      /** Max Products */
      max_products: number;
      /** Max Users */
      max_users: number;
      /** Name */
      name: string;
      /** Owner Id */
      owner_id: number;
      /** Parent Tenant Id */
      parent_tenant_id: number | null;
      /** Plan */
      plan: string;
      /** Slug */
      slug: string;
      /** Status */
      status: string;
      /** User Role */
      user_role: string | null;
    };
    /**
     * TenantMemberResponse
     * @description A tenant membership row plus the member's contact identity.
     *
     *     PII policy (deliberate, not incidental): ``user_email`` and
     *     ``user_full_name`` ARE included, because administering a tenant means
     *     administering its member accounts and an MSP admin cannot do that
     *     against opaque user ids. NO other column from the users table is
     *     exposed here — not role, not is_active, not timestamps, not
     *     password_hash — and this DTO is the only path membership data takes to a
     *     response body. Adding a column to `users` must not widen this.
     *
     *     Field set is reconciled with the webui's TenantMember interface
     *     (services/webui/src/client/types/index.ts).
     */
    TenantMemberResponse: {
      /** Id */
      id: number;
      /** Invited By Id */
      invited_by_id: number | null;
      /** Joined At */
      joined_at: string | null;
      /** Role */
      role: string;
      /** Tenant Id */
      tenant_id: number;
      /** User Email */
      user_email: string | null;
      /** User Full Name */
      user_full_name: string | null;
      /** User Id */
      user_id: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_export_audit_logs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_audit_logs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_confirm_email_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_forgot_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_oauth_connections: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_oauth_redirect: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_oauth_callback: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_disconnect_oauth: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_reset_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_list_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_revoke_session_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_dashboard_activity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_dashboard_alerts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_dashboard_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_dashboard_overview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_accept_discovered_product: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        discovery_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_scan_results: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_trigger_scan: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_hello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_hello_protected: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_license_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_backup_codes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_regenerate_backup_codes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_disable_mfa_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_setup_mfa: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_verify_mfa: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_list_products: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_register_product: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_list_product_types: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_proxy_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        connection_id: number;
        proxy_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_proxy_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        connection_id: number;
        proxy_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_proxy_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        connection_id: number;
        proxy_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_proxy_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        connection_id: number;
        proxy_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  options_proxy_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        connection_id: number;
        proxy_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patch_proxy_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        connection_id: number;
        proxy_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_product: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_update_product: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_delete_product: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_product_health: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_product_schema: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_product_tenant_mapping: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response DTO for product tenant mapping. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Connection Id */
            connection_id: number;
            /** Created At */
            created_at: string;
            /** External Id */
            external_id: string;
            /** External Kind */
            external_kind: string;
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: number;
            /** Updated At */
            updated_at: string;
          };
        };
      };
    };
  };
  put_update_product_tenant_mapping: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          /** External Id */
          external_id: string;
        };
      };
    };
    responses: {
      /** @description Response DTO for product tenant mapping. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Connection Id */
            connection_id: number;
            /** Created At */
            created_at: string;
            /** External Id */
            external_id: string;
            /** External Kind */
            external_kind: string;
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: number;
            /** Updated At */
            updated_at: string;
          };
        };
      };
    };
  };
  post_set_product_tenant_mapping: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          /** External Id */
          external_id: string;
        };
      };
    };
    responses: {
      /** @description Response DTO for product tenant mapping. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Connection Id */
            connection_id: number;
            /** Created At */
            created_at: string;
            /** External Id */
            external_id: string;
            /** External Kind */
            external_kind: string;
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: number;
            /** Updated At */
            updated_at: string;
          };
        };
      };
    };
  };
  delete_delete_product_tenant_mapping: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_test_product_connection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_list_user_teams: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_create_team_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_accept_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_team_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_update_team_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_delete_team_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_send_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_cancel_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
        invite_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_list_team_members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_add_team_member_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_update_member_role: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
        member_user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_remove_team_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_id: number;
        member_user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_list_user_tenants: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Envelope for tenant listings; rows are mixed detail/summary. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Count */
            count: number;
            /** Tenants */
            tenants: {
              [key: string]: unknown;
            }[];
          };
        };
      };
    };
  };
  post_create_tenant_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_tenant_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_update_tenant_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_delete_tenant_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_dashboard_rollup: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Provider dashboard rollup envelope. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Count */
            count: number;
            /** Rollup */
            rollup: components["schemas"]["RollupEntry"][];
          };
        };
      };
    };
  };
  get_list_tenant_members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Envelope for a tenant's membership list. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Count */
            count: number;
            /** Members */
            members: components["schemas"]["TenantMemberResponse"][];
          };
        };
      };
    };
  };
  post_add_tenant_member_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description A tenant membership row plus the member's contact identity.
       *
       *     PII policy (deliberate, not incidental): ``user_email`` and
       *     ``user_full_name`` ARE included, because administering a tenant means
       *     administering its member accounts and an MSP admin cannot do that
       *     against opaque user ids. NO other column from the users table is
       *     exposed here — not role, not is_active, not timestamps, not
       *     password_hash — and this DTO is the only path membership data takes to a
       *     response body. Adding a column to `users` must not widen this.
       *
       *     Field set is reconciled with the webui's TenantMember interface
       *     (services/webui/src/client/types/index.ts).
       */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Id */
            id: number;
            /** Invited By Id */
            invited_by_id: number | null;
            /** Joined At */
            joined_at: string | null;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: number;
            /** User Email */
            user_email: string | null;
            /** User Full Name */
            user_full_name: string | null;
            /** User Id */
            user_id: number;
          };
        };
      };
    };
  };
  put_update_tenant_member_role: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
        member_user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description A tenant membership row plus the member's contact identity.
       *
       *     PII policy (deliberate, not incidental): ``user_email`` and
       *     ``user_full_name`` ARE included, because administering a tenant means
       *     administering its member accounts and an MSP admin cannot do that
       *     against opaque user ids. NO other column from the users table is
       *     exposed here — not role, not is_active, not timestamps, not
       *     password_hash — and this DTO is the only path membership data takes to a
       *     response body. Adding a column to `users` must not widen this.
       *
       *     Field set is reconciled with the webui's TenantMember interface
       *     (services/webui/src/client/types/index.ts).
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Id */
            id: number;
            /** Invited By Id */
            invited_by_id: number | null;
            /** Joined At */
            joined_at: string | null;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: number;
            /** User Email */
            user_email: string | null;
            /** User Full Name */
            user_full_name: string | null;
            /** User Id */
            user_id: number;
          };
        };
      };
    };
  };
  delete_remove_tenant_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
        member_user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_reparent_tenant_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Parent Tenant Id */
          parent_tenant_id?: number | null;
        };
      };
    };
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_switch_tenant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description Token re-issue result for a tenant switch.
       *
       *     ``tenant`` is a full TenantDetail, not a TenantSummary. The caller has
       *     just been authorized into this tenant, so they are entitled to exactly
       *     what GET /tenants/<id> would hand them — and the webui populates its
       *     entire ``currentTenant`` from this one object (tenantStore.ts), so a
       *     summary here starves every consumer that reads it. LicenseGate.tsx falls
       *     back to "free" on a missing ``plan``, which silently hides every licensed
       *     feature from every user rather than failing visibly.
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Access Token */
            access_token: string;
            /** Scope */
            scope: string[];
            tenant: components["schemas"]["TenantDetail"];
            /** Tenant Role */
            tenant_role: string;
          };
        };
      };
    };
  };
  get_get_tenant_usage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenant_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_users: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_create_new_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_list_api_keys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_create_api_key_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_delete_api_key: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_audit_logs_endpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_profile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_update_profile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_change_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_roles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_get_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_update_existing_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_delete_existing_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_health_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_readiness_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response shape is not yet declared for this operation. The view has no @validate_response annotation, so no schema is published for it; do not rely on a specific body until one is. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
