"""Bind the portal's Tobogganing assumptions to Tobogganing's own app, everywhere.

The vendored table under ``tests/api/fixtures/tobogganing_source.json`` is what
every Tobogganing guard binds against on a machine with no product checkout. It
is generated by **booting** Tobogganing and reading ``app.url_map`` — see
:mod:`tests.api.tobogganing_route_source` for why a static parse cannot be exact
for this product.

Three things are asserted, answering different failure modes:

**Freshness.** Wherever a checkout exists the committed JSON is compared against
a live boot, so a fixture that rots is a red build with the refresh command in
the message rather than a quiet lie.

**Provenance and age.** With no checkout there is nothing to diff against, so
the recorded date is the only available signal that the product moved underneath
the table. The commit sha separates "nobody refreshed this" from "someone
refreshed it against an old checkout".

**Plausibility.** A truncated fixture would make every guard built on it pass
vacuously. The floors here catch that specifically — including a floor on the
machine-JWT routes, because a fixture that lost the ``auth`` map would silently
disarm the strongest check the Tobogganing adapter has (that no allowlist rule
points at a route the portal's credential can never satisfy).
"""

from __future__ import annotations

from typing import Final

import pytest

from product_source_fixtures import (
    MAX_FIXTURE_AGE_DAYS,
    fixture_age_days,
    fixture_path,
    load_fixture,
    source_required,
)
from tobogganing_route_source import (
    AUTH_MACHINE_JWT,
    AUTH_NODE_CREDENTIAL,
    AUTH_USER_JWT,
    FIXTURE_NAME,
    auth_table,
    boot_failure,
    machine_only_paths,
    missing_reason,
    route_table,
    tobogganing_app_module,
    vendored_auth_table,
    vendored_route_table,
)

#: Refresh instruction, quoted in every drift message so the fix is in the
#: failure rather than in a wiki page.
_REFRESH: Final[str] = "make refresh-product-source-fixtures"


def _skip_or_fail(reason: str) -> None:
    """Skip for a missing checkout — unless the job declared it has one."""
    if source_required():
        pytest.fail(reason)
    pytest.skip(reason)


class TestFixtureFreshness:
    """The vendored copy must still be what booting the product says."""

    def test_the_fixture_is_committed(self) -> None:
        """Without it, every check below degrades to a skip on a CI runner."""
        assert fixture_path(
            FIXTURE_NAME
        ).is_file(), f"{fixture_path(FIXTURE_NAME)} is missing — run `{_REFRESH}`"

    def test_vendored_routes_match_a_live_boot(self) -> None:
        """A fixture that rots silently is worse than no fixture."""
        if tobogganing_app_module() is None:
            _skip_or_fail(missing_reason())
        failure = boot_failure()
        if failure is not None:
            _skip_or_fail(failure)

        assert vendored_route_table() == route_table(), (
            f"the vendored tobogganing route table no longer matches a live "
            f"boot. Run `{_REFRESH}` and review the diff — a route Tobogganing "
            f"added, renamed or retired changes what the allowlist guards are "
            f"graded against."
        )

    def test_vendored_auth_classes_match_a_live_boot(self) -> None:
        """The auth map decides which routes can back a portal screen at all.

        A route moving from ``user`` to ``machine`` silently turns a working
        screen into a 401 for every operator. Drift here must be loud.
        """
        if tobogganing_app_module() is None:
            _skip_or_fail(missing_reason())
        failure = boot_failure()
        if failure is not None:
            _skip_or_fail(failure)

        assert vendored_auth_table() == auth_table(), (
            f"the vendored tobogganing auth map no longer matches a live boot. "
            f"Run `{_REFRESH}` and review the diff — a route whose decorator "
            f"changed may now be unreachable with the portal's credential."
        )

    def test_the_fixture_records_where_it_came_from(self) -> None:
        """Provenance is what makes a stale fixture diagnosable at all."""
        payload = load_fixture(FIXTURE_NAME)

        assert payload.get("generated_on"), f"no generation date — run `{_REFRESH}`"
        assert payload.get("source_commit"), (
            f"no source commit recorded — run `{_REFRESH}` from a git checkout "
            f"so a stale-but-recently-regenerated fixture stays diagnosable"
        )

    def test_the_fixture_is_within_the_staleness_budget(self) -> None:
        """A table nobody has refreshed stops being quietly trusted.

        This is the half of the guard that works WITHOUT a checkout, which is
        the case the vendoring exists for. Raising the budget to silence it
        defeats it — refresh the fixture, which is one make target.
        """
        age = fixture_age_days(FIXTURE_NAME)

        assert age is not None, (
            f"the vendored tobogganing fixture records no generation date, so "
            f"its staleness cannot be judged at all — run `{_REFRESH}`"
        )
        assert age <= MAX_FIXTURE_AGE_DAYS, (
            f"the vendored tobogganing route table was generated {age} days ago "
            f"(budget {MAX_FIXTURE_AGE_DAYS}). Tobogganing may have moved "
            f"underneath every guard built on it. Run `{_REFRESH}`."
        )


class TestFixturePlausibility:
    """Guard the fallback itself against being emptied."""

    def test_the_vendored_route_table_is_plausible(self) -> None:
        """A truncated fixture makes every guard built on it vacuous."""
        table = vendored_route_table()

        assert len(table) >= 100, (
            f"the vendored tobogganing route table has only {len(table)} "
            f"paths; a full boot mounts 108 distinct paths across 9 modules. "
            f"Run `{_REFRESH}`."
        )
        # One path from the core app and one from a registry-mounted module,
        # so a boot that skipped before_serving (mounting core only) fails
        # here rather than passing with two thirds of the surface missing.
        assert "/api/v1/clusters/" in table
        assert "/api/v1/sase/swg/policy" in table

    def test_the_vendored_auth_map_still_names_the_machine_routes(self) -> None:
        """The auth map is what disarms if it empties — pin its floor too.

        ``machine_only_paths`` is the input to the allowlist guard that keeps a
        rule from pointing at a route no portal token can satisfy. An empty or
        truncated auth map turns that guard into a no-op which still passes.
        """
        unreachable = machine_only_paths()

        assert len(unreachable) >= 15, (
            f"the vendored tobogganing auth map names only {len(unreachable)} "
            f"portal-unreachable routes; a full boot finds 19 (8 machine-JWT + "
            f"11 node-credential). Run `{_REFRESH}`."
        )
        # The three the 4T brief named as portal resources. Each demands
        # aud=="headend" (middleware.py:516-517), which no login token carries.
        assert "GET /api/v1/firewall/rules" in unreachable
        assert "GET /api/v1/wireguard/peers" in unreachable
        assert "GET /api/v1/headend/<headend_id>/ports" in unreachable

    def test_every_route_carries_a_known_auth_class(self) -> None:
        """An ``unknown`` classification means the classifier stopped working.

        It would silently move routes out of ``machine_only_paths`` and back
        into the allowlist's reachable set — failing open, which is the
        direction that ships.
        """
        classes = set(vendored_auth_table().values())
        known = {AUTH_MACHINE_JWT, AUTH_USER_JWT, AUTH_NODE_CREDENTIAL, "none"}

        assert classes <= known, (
            f"the vendored auth map contains unrecognised classes "
            f"{sorted(classes - known)!r} — the classifier in "
            f"tobogganing_route_source no longer understands Tobogganing's "
            f"handlers. Run `{_REFRESH}` and review."
        )
