/**
 * Drift guard for the generated API types.
 *
 * `schema.d.ts` is generated from `openapi/v1.yaml` by `npm run generate:api`.
 * Nothing forces a developer to re-run that after a backend change, and a
 * stale schema fails in the worst possible way: it still compiles, so the
 * frontend keeps type-checking against endpoints the server no longer serves
 * and silently loses types for the ones it added.
 *
 * Checked by comparing path sets rather than by re-running the generator,
 * which would need the CLI (and network on a cold cache) inside the unit
 * suite.
 */

import { readFileSync } from "fs";
import { join } from "path";

const REPO_ROOT = join(__dirname, "..", "..", "..", "..", "..", "..");
const SPEC_PATH = join(REPO_ROOT, "openapi", "v1.yaml");
const SCHEMA_PATH = join(__dirname, "..", "schema.d.ts");

/**
 * Extract the documented path strings from the OpenAPI YAML.
 *
 * A deliberate two-space-indent scan under the `paths:` key rather than a
 * YAML dependency: the file is machine-generated with stable formatting, and
 * pulling a parser into the frontend test suite to read a backend artefact
 * is more coupling than the check is worth.
 */
function specPaths(): string[] {
  const lines = readFileSync(SPEC_PATH, "utf8").split("\n");
  const found: string[] = [];
  let inPaths = false;

  for (const line of lines) {
    if (/^paths:\s*$/.test(line)) {
      inPaths = true;
      continue;
    }
    if (inPaths && /^\S/.test(line)) {
      break; // left the paths block
    }
    if (!inPaths) continue;

    const match = /^ {2}(\/[^:]*):\s*$/.exec(line);
    if (match) {
      found.push(match[1].replace(/^["']|["']$/g, ""));
    }
  }
  return found;
}

describe("generated schema.d.ts", () => {
  it("is present and marked auto-generated", () => {
    const schema = readFileSync(SCHEMA_PATH, "utf8");
    expect(schema).toContain("auto-generated by openapi-typescript");
    expect(schema).toContain("Do not make direct changes");
  });

  it("declares a path entry for every path in openapi/v1.yaml", () => {
    const schema = readFileSync(SCHEMA_PATH, "utf8");
    const paths = specPaths();

    expect(paths.length).toBeGreaterThan(30);

    const missing = paths.filter((path) => !schema.includes(`"${path}"`));
    expect(missing).toEqual([]);
  });

  it("declares no path the spec does not document", () => {
    // The other direction: a path removed from the backend must disappear
    // from the types too, or the frontend keeps compiling against an
    // endpoint that now 404s.
    const schema = readFileSync(SCHEMA_PATH, "utf8");
    const documented = new Set(specPaths());

    const declared = [...schema.matchAll(/^ {4}"(\/[^"]*)":\s*\{$/gm)].map(
      (match) => match[1],
    );
    // Restrict to the `paths` interface entries, which are the only ones
    // indented at four spaces with a leading slash.
    const extra = declared.filter((path) => !documented.has(path));
    expect(extra).toEqual([]);
  });

  it("types the login endpoint the public spec advertises", () => {
    // The one endpoint an unauthenticated client is documented to call, so
    // the generated client must be able to type it.
    const schema = readFileSync(SCHEMA_PATH, "utf8");
    expect(schema).toContain('"/api/v1/auth/login"');
    expect(schema).toContain("post_login");
  });

  it("does not type Quart's static file route", () => {
    // Excluded from the spec on purpose; if it reappeared it would show up
    // in the generated client as a first-class API operation.
    const schema = readFileSync(SCHEMA_PATH, "utf8");
    expect(schema).not.toContain('"/static/{filename}"');
  });
});
